# Generated by Django 5.0.1 on 2026-01-05 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DownloadJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        choices=[
                            ("VIDEO", "Single Video"),
                            ("PLAYLIST", "Playlist"),
                            ("CHANNEL", "Channel"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "source_url",
                    models.URLField(help_text="YouTube video / playlist / channel URL"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("QUEUED", "Queued"),
                            ("FETCHING_METADATA", "Fetching Metadata"),
                            ("DOWNLOADING", "Downloading"),
                            ("MUXING", "Muxing"),
                            ("UPLOADING", "Uploading"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=32,
                    ),
                ),
                (
                    "progress_percentage",
                    models.FloatField(default=0.0, help_text="0.0 to 100.0"),
                ),
                ("retry_count", models.PositiveIntegerField(default=0)),
                ("max_retries", models.PositiveIntegerField(default=3)),
                (
                    "error_code",
                    models.TextField(
                        blank=True,
                        help_text="Short machine-readable failure reason",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Human-readable failure details",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="jobs.downloadjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status"], name="jobs_downlo_status_acd97a_idx"
                    ),
                    models.Index(
                        fields=["job_type"], name="jobs_downlo_job_typ_8ce1bb_idx"
                    ),
                ],
            },
        ),
    ]
