# Generated by Django 5.0.1 on 2026-01-06 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="downloadjob",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("DISCOVERING", "Discovering"),
                    ("FETCHING_METADATA", "Fetching metadata"),
                    ("DOWNLOADING", "Downloading"),
                    ("PAUSED", "Paused"),
                    ("CANCELLED", "Cancelled"),
                    ("COMPLETED", "Completed"),
                    ("FAILED", "Failed"),
                ],
                db_index=True,
                default="PENDING",
                max_length=32,
            ),
        ),
    ]
