# Generated by Django 5.0.1 on 2026-01-05 18:52

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "youtube_id",
                    models.CharField(
                        db_index=True,
                        help_text="YouTube video ID",
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("title", models.TextField()),
                ("channel_id", models.CharField(db_index=True, max_length=64)),
                ("channel_name", models.TextField()),
                (
                    "duration_seconds",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("upload_date", models.DateField(blank=True, null=True)),
                ("view_count", models.BigIntegerField(blank=True, null=True)),
                ("like_count", models.BigIntegerField(blank=True, null=True)),
                ("raw_metadata", models.JSONField()),
                (
                    "extracted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="video_metadata",
                        to="jobs.downloadjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-extracted_at"],
                "indexes": [
                    models.Index(
                        fields=["youtube_id"], name="media_video_youtube_d62a68_idx"
                    ),
                    models.Index(
                        fields=["channel_id"], name="media_video_channel_be65e1_idx"
                    ),
                    django.contrib.postgres.indexes.GinIndex(
                        fields=["raw_metadata"], name="media_video_raw_met_7b1169_gin"
                    ),
                ],
            },
        ),
    ]
